---
# script:
#     - docker run -e CI=true USERNAME/react-test npm test
sudo: required
services:
  - docker

before_install:
  - docker build -t antonsmit30/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run antonsmit30/react-test npm test -- --coverage

after_success:
  - docker build -t antonsmit30/multi-client ./client
  - docker build -t antonsmit30/multi-nginx ./nginx
  - docker build -t antonsmit30/multi-server ./server
  - docker build -t antonsmit30/multi-worker ./worker
  # ensure you are logged in with docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push to docker hub
  - docker push antonsmit30/multi-client
  - docker push antonsmit30/multi-nginx
  - docker push antonsmit30/multi-server
  - docker push antonsmit30/multi-worker